#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "System restart" {
	echo "System rebooting..."
	reboot
}

menuentry "AB2015 Kernel" {
	# fix the partition number, after showing that it does not boot by pressing e
	set root=(hd0,5)
	# bzimage location
	linux /boot/vmlinuz-3.17.6RC1 root=/dev/sda1
	# initrd is the drivers that the kerel needs
	initrd /boot/initrd.img-3.17.6RC1
	boot
}
